name: Test Actions                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - test_actions
env:
  AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
  ZPUBLIC: ${{ secrets.ZPUBLIC }}
  ZSECRET: ${{ secrets.ZSECRET }}
  ZNETWORK: ${{ secrets.ZNETWORK }}

jobs:
  build:
    runs-on: ubuntu-latest          
    #container:
    #  image: ubuntu:latest
    #  options: --user root --cap-add NET_ADMIN --cap-add=SYS_ADMIN --device=/dev/net/tun
    steps:
      - run: |
          sudo apt update
          sudo apt install gnupg curl -y
          sudo curl -s https://install.zerotier.com | bash
          sudo zerotier-cli status
          sudo echo "$AUTHTOKEN" > /var/lib/zerotier-one/authtoken.secret
          sudo echo "$ZPUBLIC" > /var/lib/zerotier-one/identity.public
          sudo echo "$ZSECRET" > /var/lib/zerotier-one/identity.secret
          sudo service zerotier-one restart
          sudo sleep 1
          sudo zerotier-cli join $ZNETWORK
          sudo zerotier-cli status
