name: Test Actions                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - test_actions

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: |
          sudo curl -s https://install.zerotier.com | sudo bash
          ls -lha /var/lib/zerotier-one/
          sudo cat /var/lib/zerotier-one/authtoken.secret
          sudo cat /var/lib/zerotier-one/identity.public
          sudo cat /var/lib/zerotier-one/identity.secret
          sudo zerotier-cli status
