name: Test Actions                                  

on: #Testt
  push:                                       
    branches:                                
      - test_actions
env:
  AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
  ZPUBLIC: ${{ secrets.ZPUBLIC }}
  ZSECRET: ${{ secrets.ZSECRET }}
  ZNETWORK: ${{ secrets.ZNETWORK }}
  ZEROTIER_API_SECRET: ${{ secrets.AUTHTOKEN }}
  ZEROTIER_IDENTITY_PUBLIC: ${{ secrets.ZPUBLIC }}
  ZEROTIER_IDENTITY_SECRET: ${{ secrets.ZSECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker container ls
      - run: docker run -d --name myzerotier --rm --cap-add NET_ADMIN -e ZEROTIER_IDENTITY_SECRET -e ZEROTIER_API_SECRET -e ZEROTIER_IDENTITY_PUBLIC --device /dev/net/tun zerotier/zerotier:latest $ZNETWORK
      - run: docker container ls
      - run: sleep 120
      - run: ping -c 10 10.243.148.184
