name: Test Actions                                  

on:
  push:                                       
    branches:                                
      - test_actions
env:
  AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
  ZPUBLIC: ${{ secrets.ZPUBLIC }}
  ZSECRET: ${{ secrets.ZSECRET }}
  ZNETWORK: ${{ secrets.ZNETWORK }}
  ZEROTIER_API_SECRET: "qolrasv2b5ydy1g2xqtoylf8"
  ZEROTIER_IDENTITY_PUBLIC: "67403aa382:0:cbde12aafad6aa9fd87295f751e872805a66535a774f313b8967aa2badff4d617e30703aa50fee793cf39ccba906f7e16d83d5d75ef86614a1aa38211bfb45ab"
  ZEROTIER_IDENTITY_SECRET: "67403aa382:0:cbde12aafad6aa9fd87295f751e872805a66535a774f313b8967aa2badff4d617e30703aa50fee793cf39ccba906f7e16d83d5d75ef86614a1aa38211bfb45ab:a419f29c737766ac00463e0b8dd07ce734be29494ff153ccaf2bee048e2ad72bfefc34f26f41dce1931d012bec5269cfadea02fbf2031918534cb0d22506ff10"

jobs:
  build:
    runs-on: ubuntu-latest          
    #container:
    #  image: ubuntu:latest
    #  options: --user root --cap-add NET_ADMIN --cap-add=SYS_ADMIN --device=/dev/net/tun
    steps:
      - run: |
          docker container ls
          docker run --name myzerotier --rm --cap-add NET_ADMIN -e $ZEROTIER_IDENTITY_SECRET -e $ZEROTIER_API_SECRET -e $ZEROTIER_IDENTITY_PUBLIC --device /dev/net/tun zerotier/zerotier:latest $ZNETWORK
          #sudo apt update
          #sudo apt install gnupg curl -y
          #sudo curl -s https://install.zerotier.com | bash
          #sudo zerotier-cli status
          #sudo service zerotier-one stop
          #sudo ls -lha /var/lib/zerotier-one/
          #sudo su zerotier-one -c echo "$AUTHTOKEN" > /var/lib/zerotier-one/authtoken.secret
          #sudo su zerotier-one -c echo "$ZPUBLIC" > /var/lib/zerotier-one/identity.public
          #sudo su zerotier-one -c echo "$ZSECRET" > /var/lib/zerotier-one/identity.secret
          #sudo service zerotier-one start
          #sudo sleep 1
          #sudo zerotier-cli join $ZNETWORK
          #sudo zerotier-cli status
