name: Test Actions                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - test_actions
env:
  AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
  ZPUBLIC: ${{ secrets.ZPUBLIC }}
  ZSECRET: ${{ secrets.ZSECRET }}

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    container:
      image: ubuntu:latest
      options: --user root
    steps:
      - run: |
          apt update
          apt install curl -y
          curl -s https://install.zerotier.com | sudo bash
          ls -lha /var/lib/zerotier-one/
          cat /var/lib/zerotier-one/authtoken.secret
          echo ""
          cat /var/lib/zerotier-one/identity.public
          echo ""
          cat /var/lib/zerotier-one/identity.secret
          echo ""
          zerotier-cli status
          systemctl stop zerotier-one
          echo $AUTHTOKEN > /var/lib/authtoken.secret
          echo $ZPUBLIC > /var/lib/identity.public
          echo $ZSECRET > /var/lib/identity.secret
