name: Test Actions                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - test_actions
env:
  AUTHTOKEN: ${{ secrets.AUTHTOKEN }}
  ZPUBLIC: ${{ secrets.ZPUBLIC }}
  ZSECRET: ${{ secrets.ZSECRET }}
  ZNETWORK: ${{ secrets.ZNETWORK }}

jobs:
  build:
    runs-on: ubuntu-latest          
    #container:
    #  image: ubuntu:latest
    #  options: --user root --cap-add NET_ADMIN --cap-add=SYS_ADMIN --device=/dev/net/tun
    steps:
      - run: |
          apt update
          apt install gnupg curl -y
          curl -s https://install.zerotier.com | bash
          zerotier-cli status
          echo "$AUTHTOKEN" > /var/lib/zerotier-one/authtoken.secret
          echo "$ZPUBLIC" > /var/lib/zerotier-one/identity.public
          echo "$ZSECRET" > /var/lib/zerotier-one/identity.secret
          service zerotier-one restart
          sleep 1
          zerotier-cli join $ZNETWORK
          zerotier-cli status
