name: Test Actions                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - test_actions

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - name: Install an use Zerotier
      - run: |
          curl -s https://install.zerotier.com | sudo bash
          ls -lha /var/lib/zerotier-one/
          zerotier-cli status
